name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    name: Hassfest
    steps:
      - name: "Check out the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Run hassfest validation"
        uses: "home-assistant/actions/hassfest@master"

  hacs:
    runs-on: "ubuntu-latest"
    name: HACS
    steps:
      - name: "Check out the repository"
        uses: "actions/checkout@v4.1.1"

      - name: "Run HACS validation"
        uses: "hacs/action@main"
        with:
          category: "integration"
          ignore: "brands"